var HRSTGAME_ANALYTICS = {
	region: "us-east-1",
	poolId: "us-east-1:f5ca6444-9825-407e-815e-fe7e62b6fb05",
	appId: "c6ee32159a0e4c2a98b238b69ebb3c70",
	appTitle: "Hearst Interactive Player - Prod",
	appVersionName: "1.5.6",
	kinesisEPStreamName: "editorial-polls-stream-prod",
	kinesisStreamName: "hearst-owned-stream-prod",
	shareDomain: "games.hearstgames.com",
	gamesApiUrl: "https://joker.hearstgames.com",
	env: "production",
	achievementStars: true,
	showLoadingScreen: true,
	showLeftRailSocket: "true",
	progressType: "mark",
	home_url: "",
	twitterHandle: "",
	ignoredEvents: [
		"Tile Moved"
	],
	interstitialAd: {
		enabled: true,
		frequency: 3,
		countdown: 5
	},
	recircVersion: 'blind',
	skipBehavior: 'default',
	skipBundleSummaries: true,
	timedScore: false,
	debug: 'silent',
	soundEnabled: false,
	categorySwitcher: false,
	enableHIPS: true,
	hipsPrefix: "https://hips.hearstapps.com/hearst-owned-prod.s3-website-us-east-1.amazonaws.com",
	bundleSeeAllButton: false,
	marketingPollsLimit: "7",
	audienceSegmentsRequestLimit: "50",
	viewedMarketingPollTimeToLive: "1",
	viewedMarketingPollTimeToLiveUnit: "M",
	excludedMarketingPollsLimit: "50",
	lotameAudienceUrl: "ad.crwdcntrl.net/5/c=4290/pe=y/callback=segmentCallback",
	ensightenUrl: "//nexus.ensighten.com/hearst/riddler/Bootstrap.js",
	ensightenDevUrl: "//nexus.ensighten.com/hearst/riddler_dev/Bootstrap.js",
	defaultBrand: "cosmopolitan",
};
